
server:
    port: 8090
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/database_db
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                enable_lazy_load_no_trans: true
                jdbc:
                    lob:
                        non_contextual_creation: true
    session:
        jdbc:
            initialize-schema: always

    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 213566823206-41tabfjin9jik5euu7ncehf1s4ac2v0e.apps.googleusercontent.com
                        clientSecret: QQsB4Mc24YT_3Ytg4ldvnkPI


springdoc:
    swagger-ui:
        path: /swagger-ui.html
